### ISSUE TITLE
Error in #major method

### ISSUE THREAD

**Issue by jsmestad** [jimeh/build-emacs-for-macos#13]
```
./build-emacs-for-macos feature/native-comp

==> INFO: Downloading tarball from GitHub. This could take a while, please be patient.
==> CMD: curl -L https://github.com/emacs-mirror/emacs/tarball/15acd27d1c0de8b56bab61daa0a8fcd4fef0fdc4 -o /Users/jsmestad/code/github/build-emacs-for-macos/tarballs/emacs-mirror-emacs-15acd27.tgz
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   167    0   167    0     0    530      0 --:--:-- --:--:-- --:--:--   530
100 40.3M    0 40.3M    0     0  1185k      0 --:--:--  0:00:34 --:--:-- 1118k
==> INFO: Extracting tarball...
==> CMD: tar -xzf /Users/jsmestad/code/github/build-emacs-for-macos/tarballs/emacs-mirror-emacs-15acd27.tgz -C /Users/jsmestad/code/github/build-emacs-for-macos/sources
==> CMD: mkdir -p /Users/jsmestad/code/github/build-emacs-for-macos/sources/emacs-mirror-emacs-15acd27/macos_patches
==> INFO: Downloading patch: https://github.com/d12frosted/homebrew-emacs-plus/raw/master/patches/emacs-28/fix-window-role.patch
==> CMD: curl -L# https://github.com/d12frosted/homebrew-emacs-plus/raw/master/patches/emacs-28/fix-window-role.patch -o /Users/jsmestad/code/github/build-emacs-for-macos/sources/emacs-mirror-emacs-15acd27/macos_patches/patch-001.diff
################################################################################################### 100.0%################################################################################################### 100.0%
==> INFO: Applying patch...
==> CMD: patch -f -p1 -i /Users/jsmestad/code/github/build-emacs-for-macos/sources/emacs-mirror-emacs-15acd27/macos_patches/patch-001.diff
patching file src/nsterm.m
Hunk #1 succeeded at 8762 (offset -6 lines).
==> CMD: mkdir -p /Users/jsmestad/code/github/build-emacs-for-macos/sources/emacs-mirror-emacs-15acd27/macos_patches
==> INFO: Downloading patch: https://github.com/d12frosted/homebrew-emacs-plus/raw/master/patches/emacs-28/system-appearance.patch
==> CMD: curl -L# https://github.com/d12frosted/homebrew-emacs-plus/raw/master/patches/emacs-28/system-appearance.patch -o /Users/jsmestad/code/github/build-emacs-for-macos/sources/emacs-mirror-emacs-15acd27/macos_patches/patch-002.diff
################################################################################################### 100.0%
==> INFO: Applying patch...
==> CMD: patch -f -p1 -i /Users/jsmestad/code/github/build-emacs-for-macos/sources/emacs-mirror-emacs-15acd27/macos_patches/patch-002.diff
patching file src/frame.h
patching file src/nsfns.m
Hunk #1 succeeded at 1253 (offset -16 lines).
patching file src/nsterm.m
Hunk #1 succeeded at 2217 (offset 14 lines).
Hunk #2 succeeded at 5712 (offset 28 lines).
Hunk #3 succeeded at 5958 (offset 28 lines).
Hunk #4 succeeded at 6003 (offset 28 lines).
Hunk #5 succeeded at 6211 (offset 28 lines).
Hunk #6 succeeded at 9070 (offset 21 lines).
Hunk #7 succeeded at 9952 (offset 21 lines).
==> CMD: ./autogen.sh
Checking whether you have the necessary tools...
(Read INSTALL.REPO for more details on building Emacs)
Checking for autoconf (need at least version 2.65) ... ok
Your system has the required tools.
Building aclocal.m4 ...
Running 'autoreconf -fi -I m4' ...
You can now run './configure'.
==> INFO: Detecting native-comp support: Supported
==> INFO: Compiling from source. This will take a while...
==> INFO: Compiling with native-comp enabled

Traceback (most recent call last):
	7: from ./build-emacs-for-macos:871:in `<main>'
	6: from ./build-emacs-for-macos:103:in `build'
	5: from ./build-emacs-for-macos:249:in `compile_source'
	4: from /Users/jsmestad/.asdf/installs/ruby/2.7.1/lib/ruby/2.7.0/fileutils.rb:139:in `cd'
	3: from /Users/jsmestad/.asdf/installs/ruby/2.7.1/lib/ruby/2.7.0/fileutils.rb:139:in `chdir'
	2: from ./build-emacs-for-macos:285:in `block in compile_source'
	1: from ./build-emacs-for-macos:53:in `to_s'
./build-emacs-for-macos:57:in `major': undefined method `[]' for nil:NilClass (NoMethodError)
```

**Comment by jimeh** [comment]
Now that's interesting.

What version of macOS are you running? And what do you get if you run this:

```
sw_vers -productVersion
```

**Comment by jsmestad** [comment]
I am running on Big Sur beta

**Comment by jimeh** [comment]
I just pushed a fix that should address this. It seems the version is just `11.0` on Big Sur, and my code assumed there was always three numbers separated by dots.
