### ISSUE TITLE
Problem embedding libraries into Emacs.app

### ISSUE THREAD

**Issue by ashton314** [jimeh/build-emacs-for-macos#23]
After running `./build-emacs-for-macos --git-sha fd9e9308d27138a16e2e93417bd7ad4448fea40a feature/native-comp`, everything seems to compile alright, but then I get the following error:

```
==> INFO: Embedding libraries into Emacs.app
Traceback (most recent call last):
	17: from ./build-emacs-for-macos:814:in `<main>'
	16: from ./build-emacs-for-macos:101:in `build'
	15: from ./build-emacs-for-macos:589:in `embed'
	14: from /usr/local/Cellar/ruby/2.7.2/lib/ruby/2.7.0/fileutils.rb:139:in `cd'
	13: from /usr/local/Cellar/ruby/2.7.2/lib/ruby/2.7.0/fileutils.rb:139:in `chdir'
	12: from ./build-emacs-for-macos:591:in `block in embed'
	11: from ./build-emacs-for-macos:631:in `copy_extra_libs'
	10: from ./build-emacs-for-macos:631:in `each'
	 9: from ./build-emacs-for-macos:636:in `block in copy_extra_libs'
	 8: from /usr/local/Cellar/ruby/2.7.2/lib/ruby/2.7.0/fileutils.rb:429:in `cp'
	 7: from /usr/local/Cellar/ruby/2.7.2/lib/ruby/2.7.0/fileutils.rb:1587:in `fu_each_src_dest'
	 6: from /usr/local/Cellar/ruby/2.7.2/lib/ruby/2.7.0/fileutils.rb:1603:in `fu_each_src_dest0'
	 5: from /usr/local/Cellar/ruby/2.7.2/lib/ruby/2.7.0/fileutils.rb:1589:in `block in fu_each_src_dest'
	 4: from /usr/local/Cellar/ruby/2.7.2/lib/ruby/2.7.0/fileutils.rb:430:in `block in cp'
	 3: from /usr/local/Cellar/ruby/2.7.2/lib/ruby/2.7.0/fileutils.rb:511:in `copy_file'
	 2: from /usr/local/Cellar/ruby/2.7.2/lib/ruby/2.7.0/fileutils.rb:1414:in `copy_file'
	 1: from /usr/local/Cellar/ruby/2.7.2/lib/ruby/2.7.0/fileutils.rb:1414:in `open'
/usr/local/Cellar/ruby/2.7.2/lib/ruby/2.7.0/fileutils.rb:1414:in `initialize': No such file or directory @ rb_sysopen - /usr/local/opt/libiconv/lib/libiconv.2.dylib (Errno::ENOENT)
```

ruby --version: `ruby 2.7.2p137 (2020-10-01 revision 5445e04352) [x86_64-darwin19]`

I found the compiled app; the app itself launches just fine, but I get an error message on opening:
```
File is missing: Opening directory, No such file or directory, /Users/ashton/Sync/repos/build-emacs-for-macos/sources/emacs-mirror-emacs-fd9e930/nextstep/Emacs.app/Contents/MacOS/lib/gcc
```

(Also, my `.emacs` didn't load.)

**Comment by ashton314** [comment]
Solution: run `brew install libiconv`. This puts the file in place. (No need to force linkage.)

**Comment by jimeh** [comment]
If you haven't done so, I'd suggest running `brew bundle` before the build script to ensure you have all the homebrew dependencies listed in the `Brewfile`.
