### ISSUE TITLE
Ruby error when creating symlinks for native-comp

### ISSUE THREAD

**Issue by spencerking** [jimeh/build-emacs-for-macos#28]
I ran `./build-emacs-for-macos --git-sha 33b8ce865fcfd58538ae2d7c3fff04998fcd3330 feature/native-comp` and received the following error:

```
==> INFO: Creating symlinks within Emacs.app needed for native-comp
Traceback (most recent call last):
	6: from ./build-emacs-for-macos:814:in `<main>'
	5: from ./build-emacs-for-macos:99:in `build'
	4: from ./build-emacs-for-macos:360:in `symlink_internals'
	3: from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/fileutils.rb:128:in `cd'
	2: from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/fileutils.rb:128:in `chdir'
	1: from ./build-emacs-for-macos:365:in `block in symlink_internals'
./build-emacs-for-macos:365:in `basename': no implicit conversion of nil into String (TypeError)
```

**Comment by spencerking** [comment]
I'm assuming the issue is:
```
/usr/bin/install: illegal option -- D
usage: install [-bCcpSsv] [-B suffix] [-f flags] [-g group] [-m mode]
               [-o owner] file1 file2
       install [-bCcpSsv] [-B suffix] [-f flags] [-g group] [-m mode]
               [-o owner] file1 ... fileN directory
       install -d [-v] [-g group] [-m mode] [-o owner] directory ...
```

The macOS provided version of `install` does not have `-D`.

**Comment by spencerking** [comment]
Sorry about all of the updates, installing GNU coreutils now gets me to this error:
```
Traceback (most recent call last):
	17: from ./build-emacs-for-macos:814:in `<main>'
	16: from ./build-emacs-for-macos:101:in `build'
	15: from ./build-emacs-for-macos:596:in `embed'
	14: from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/fileutils.rb:128:in `cd'
	13: from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/fileutils.rb:128:in `chdir'
	12: from ./build-emacs-for-macos:598:in `block in embed'
	11: from ./build-emacs-for-macos:638:in `copy_extra_libs'
	10: from ./build-emacs-for-macos:638:in `each'
	 9: from ./build-emacs-for-macos:643:in `block in copy_extra_libs'
	 8: from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/fileutils.rb:418:in `cp'
	 7: from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/fileutils.rb:1555:in `fu_each_src_dest'
	 6: from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/fileutils.rb:1571:in `fu_each_src_dest0'
	 5: from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/fileutils.rb:1557:in `block in fu_each_src_dest'
	 4: from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/fileutils.rb:419:in `block in cp'
	 3: from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/fileutils.rb:492:in `copy_file'
	 2: from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/fileutils.rb:1385:in `copy_file'
	 1: from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/fileutils.rb:1385:in `open'
/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/fileutils.rb:1385:in `initialize': No such file or directory @ rb_sysopen - /usr/local/opt/expat/lib/libexpat.1.dylib (Errno::ENOENT)
```

**Comment by jimeh** [comment]
@spencerking No worries :)

It looks like you're missing various Homebrew dependencies. Have you run `brew bundle` from the root of the `build-emacs-for-macos` folder?

**Comment by spencerking** [comment]
@jimeh You're right, I completely skipped over the step. Everything is working now.
